name: clickup
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple ClickUp web application wrapper
description: |
    This is a simple electron container for official ClickUp web application: https://app.clickup.com

confinement: strict
grade: devel

parts:
  electron-app:
    plugin: nodejs
    build: npm install && npm run dist
    source: .

environment:
    TMPDIR: $XDG_RUNTIME_DIR